# Generated by Django 5.0.6 on 2024-05-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thoughts',
            name='content',
            field=models.CharField(max_length=300),
        ),
    ]
